name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true  # Recursively checkout submodules
        fetch-depth: 0    # Needed for full history (useful for submodules with branches)
    - name: make test-c
      run: make test-c
    - name: make lint
      run: make lint
